### PR TITLE
+35 additional Firmware binaries

### PR DESCRIPTION
**Pull request by MatrixEditor**
+ 35 ISU-binaries
+ README update with structure of the download URL for newer products

### CODE REVIEW

**Comment by cweiske** [comment]
The known_versions.txt firmware list was sorted by a) module (FS2026 before FS2340) and b) by chip (0200 before 0500) and c) by device id. Your list changes seem to have no order at all.

**Comment by MatrixEditor** [comment]
Now the known-versions.txt file contains the version names shown on the radio screens (sorted descending).

**Comment by cweiske** [comment]
The diff looks better now. But when looking at the diff, some known versions have been removed. Why?

**Comment by MatrixEditor** [comment]
Actually, there was only one version missing - has been added to the pull request.

**Comment by cweiske** [comment]
Thanks for the patch! I've merged it.

**Pull request closed without merging**
