### PR TITLE
Added 43 new firmware binaries

### PR DESCRIPTION
**Pull request by MatrixEditor**
The additional firmware files include new interface specifications:

    ir-ser
    ir-fsccp-sbc
    ir-mmi-16m

as well as new firmware for the following modules:

    FS2028
    FS2026
    FS2340

Unfortunately, these version numbers were taken from a data-blob [here](https://www.kaggle.com/code/somnambwl/cybersecurity/notebook), so there is no device specification linked to it.

### CODE REVIEW

**Comment by cweiske** [comment]
please rebase against master.

**Comment by MatrixEditor** [comment]
Rebase against the upstream/master branch wasn't possible - git failed to merge in the changes.

**Comment by cweiske** [comment]
Do an interactive rebase (git rebase -i) and throw away the commits that are already in master.

**Comment by MatrixEditor** [comment]
The changes should be visible now.

**Comment by cweiske** [comment]
No, they are not. You must force-push after rebasing.

**Comment by cweiske** [comment]
There should be only one commit here in the pull request after pushing the rebased branch.

**Comment by lclol** [comment]
Sorry I'm note used to GitHub, and I don't know if it's the right place to give this information. My excuses if not. 
FS2340-0000-0146 is the reference for Grundig DTR 6000 X [https://www.grundig.com/de-de/audio/radios/digital-internetradios/dtr-6000-x-schwarz](url)

On my device, latest FW is ir-cui-FS2340-0000-0146_V4.5.13.707296-1A22

As far as I understand, these mean that the device is based on Venice-X card, but I've not been able to run undok with it. Nmap returns two open ports, 80 and 8080, which may explain why the device isn't detected by undok.

**Comment by MatrixEditor** [comment]
UNDOK uses mDNS (Multicast DNS) and UPnP to search for devices in the LAN over UDP Broadcast. If that fails, no device will be available to work with. The ports you've discovered are mapped to HTTP and UPnP - there is nothing wrong with that. 

The device **SHOULD** be visible if it's active and in the same network. Any errors may be caused by bug(s) in the running firmware.

**Comment by lclol** [comment]
Thaks @MatrixEditor :) I've asked Frontier Silicon support, and their answear is kind of interesting. They tell me that the radio is not supported by undok because grundig did not request such support. So it looks like some firmwares might be limited depending on the features the "manufacturer"/brand wants (pays ?) for each device.

**Comment by cweiske** [comment]
Closing because nothing changed since months.

**Pull request closed without merging**
